-- Preserve catalog IDs and data when upgrading the original platform.
DO $$
BEGIN
    IF to_regclass('public.apps') IS NULL AND to_regclass('public.projects') IS NOT NULL THEN
        ALTER TABLE projects RENAME TO apps;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS apps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    path VARCHAR(64) NOT NULL,
    title VARCHAR(128),
    description VARCHAR(2048)
);

UPDATE apps SET path = 'core-design' WHERE path = 'core';
